# -*- coding: utf-8 -*-
"""connect4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIa6WblnVVB2xtStZErv-0Vtzvy14Us1
"""

import numpy as np

ROWS, COLS = 6, 7

class C4:
    def __init__(self):
        self.board = np.zeros((ROWS, COLS), dtype=np.int8)
        self.player = 1
        self.done = False
        self.winner = 0
        self.moves = 0

    def clone(self):
        c = C4()
        c.board[:] = self.board
        c.player = self.player
        c.done = self.done
        c.winner = self.winner
        c.moves = self.moves
        return c

    def legal_actions(self):
        return [c for c in range(COLS) if self.board[0, c] == 0]

    def step(self, a: int):
        if self.done:
            return
        if a not in self.legal_actions():
            self.done = True
            self.winner = -self.player
            return
        r = ROWS - 1
        while r >= 0 and self.board[r, a] != 0:
            r -= 1
        self.board[r, a] = self.player
        self.moves += 1
        if self._is_win(r, a):
            self.done = True
            self.winner = self.player
        elif self.moves >= ROWS * COLS:
            self.done = True
            self.winner = 0
        else:
            self.player *= -1

    def _is_win(self, r, c):
        pl = self.player
        b = self.board
        for dr, dc in [(1,0),(0,1),(1,1),(1,-1)]:
            cnt = 1
            rr, cc = r+dr, c+dc
            while 0<=rr<ROWS and 0<=cc<COLS and b[rr,cc]==pl:
                cnt+=1; rr+=dr; cc+=dc
            rr, cc = r-dr, c-dc
            while 0<=rr<ROWS and 0<=cc<COLS and b[rr,cc]==pl:
                cnt+=1; rr-=dr; cc-=dc
            if cnt >= 4:
                return True
        return False

    def to_obs(self):
        ours   = (self.board == self.player).astype(np.float32)
        theirs = (self.board == -self.player).astype(np.float32)
        ones   = np.ones_like(ours, dtype=np.float32)
        return np.stack([ours, theirs, ones], axis=0)